name: rls
on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: |
          zip -rv9 ./abootloop.zip ./* -x ./.git ./.github ./README.md \ 
                                          ./update.json ./changelog
      - name: Releasing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cat ./module.prop | tr -d ' ' | sudo tee /dev/shm/modprop > /dev/null
          . /dev/shm/modprop
          gh release create "$version" ./abootloop.zip -F ./changelog
      - name: Updating service files
        run: |
          . /dev/shm/modprop
          python3 ./.github/mkjson "$version" "$versionCode" "$zipUrl" "$changelog"
          
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./update.json
          git commit -m 'JSON update'
          git push
